# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9b74ef50c099941223f208f30df5c50cd85f00447deb5cc42958528d09bd6be2e564423c420ac1890739d783822ef53daa6864f20f080fa0f037d170265f40

test:
  secret_key_base: 71c880c4af3bbe4d9ac09f39c547804a98ce7cb76d5aacdf7bfe4d22122c655874d0a52191864766eb499a51b59303fa72189e75dc59ef23e1e6c5ff5e9f2136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
